version: v0.8.0-alpha.2

log:
  level: debug

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: cockroach://root@localhost:26257/defaultdb?sslmode=disable

namespaces:
  - name: default
    id: 1
