version: "3"

services:
#  keto-migrate-v0.8:
#    image: oryd/keto:v0.8.0-alpha.2
#    links:
#      - cockroach:cockroach
#    volumes:
#      - type: bind
#        source: ./config
#        target: /home/ory
#    environment:
#      - LOG_LEVEL=debug
#      - DSN=cockroach://root@cockroach:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
#    command: [ "migrate", "up", "-y", "-c", "/home/ory/keto.yml" ]
#    restart: on-failure

  keto-v0.8:
    image: oryd/keto:v0.8.0-alpha.2
    links:
      - cockroach:cockroach
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    ports:
      - "4466:4466"
      - "4467:4467"
    depends_on:
      - keto-migrate
    environment:
      - DSN=cockroach://root@cockroach:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: on-failure
    command: serve -c /home/ory/keto.yml

#  init-tuples:
#    image: oryd/keto:v0.8.0-alpha.2
#    links:
#      - keto-v0.8:keto
#    volumes:
#      - type: bind
#        source: ./config
#        target: /home/ory
#    entrypoint: "/home/ory/create-tuples.sh"
#    command: ""
#    restart: on-failure
#    environment:
#      - KETO_READ_REMOTE=keto:4466
#      - KETO_WRITE_REMOTE=keto:4467

  cockroach:
    image: cockroachdb/cockroach:v22.1.2
    volumes:
      - "./cockroach-data:/cockroach/cockroach-data"
    ports:
      - "8080:8080"
      - "26257:26257"
    command:
      - start-single-node
      - --insecure
